# Site Settings
title: tetretalk
email: youremail@xyz.com
description: Play Millions of games created from users just like you! Different games for different ages! Come check out the site and consider joining our discord to know when a game is updated or when we are adding something!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Tetretalk
user_description: Tetretalk
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Rules
    url: /rules/
  - title: Jobs
    url: /jobs/
  - title: Sponsors
    url: /sponsors/
  - title: Create
    url: /create/
  - title: TetreTime Live
    url: /live/
  - title: Website Updates
    url: /updates/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
